# Generated by Django 3.2.6 on 2021-08-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_type', models.CharField(max_length=1, verbose_name='답변 유형')),
                ('a_text', models.TextField(verbose_name='답변 텍스트')),
            ],
        ),
        migrations.CreateModel(
            name='Mbti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_i', models.IntegerField(default=0, verbose_name='E/I')),
                ('s_n', models.IntegerField(default=0, verbose_name='S/N')),
                ('t_f', models.IntegerField(default=0, verbose_name='T/F')),
                ('p_j', models.IntegerField(default=0, verbose_name='P/J')),
            ],
        ),
        migrations.CreateModel(
            name='MbtiText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='mbti 세부 텍스트')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(max_length=4, verbose_name='mbti 유형')),
                ('song', models.TextField(verbose_name='노래 제목')),
                ('singer', models.TextField(verbose_name='가수')),
                ('close_line', models.TextField(verbose_name='마무리 멘트')),
                ('description', models.TextField(verbose_name='장면 묘사')),
                ('heart', models.TextField(verbose_name='속마음')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.mbtitext', verbose_name='mbti 특징')),
                ('partner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.result', verbose_name='결이 같은 사람')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.IntegerField(verbose_name='No.')),
                ('q_title', models.TextField(verbose_name='질문')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.answer', verbose_name='답변')),
            ],
        ),
    ]
