# Generated by Django 3.2.6 on 2021-09-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_mbti_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbti',
            name='hash_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
